### ISSUE TITLE
get_departure_timers return error 404

### ISSUE THREAD

**Issue by smar000** [ardevd/jlrpy#111]
Hi again

When I call `get_departure_timers()`, I am getting an HTTP error 404. This is on a 2022 I-Pace. Is this another of those header change issues or some other limitation of the I-Pace?

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/scripts/jlr2mqtt/jlrpy.py", line 243, in get_departure_timers
    return self.get("departuretimers", headers)
  File "/opt/scripts/jlr2mqtt/jlrpy.py", line 639, in get
    return self.connection.get(command, '%s/vehicles/%s' % (IF9_BASE_URL, self.vin), headers)
  File "/opt/scripts/jlr2mqtt/jlrpy.py", line 71, in get
    return self.post(command, url, headers, None)
  File "/opt/scripts/jlr2mqtt/jlrpy.py", line 80, in post
    return self.__open("%s/%s" % (url, command), headers=headers, data=data)
  File "/opt/scripts/jlr2mqtt/jlrpy.py", line 102, in __open
    resp = opener.open(req)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Thanks

**Comment by smar000** [comment]
Closing as the departure timers are correctly coming through.
