### ISSUE TITLE
Login user issues when used with homeassistant-jlrincontrol

### ISSUE THREAD

**Issue by pmharris77** [ardevd/jlrpy#126]
I am using jlrpy indirectly via the `homeassistant-jlrincontrol` HomeAssistant integration.  Has been working fine since I installed it, however, after rebooting HomeAssistant, I now get the following error raised from within jlrpy.

Any ideas what could be causing it?  I have tried connecting using jlrpy directly with the exact same call signature to jlrpy.Connection() and I cannot reproduce the issue.

`homeassistant-jlrincontrol` calls it like this:

`partial(jlrpy.Connection, self.email, self.password, '' , '', self.use_china_servers)`

Also, are there any plans to add in exception handling for failures in auth, device registration and user log in?

```
Logger: custom_components.jlrincontrol
Source: custom_components/jlrincontrol/__init__.py:396
integration: Jaguar Landrover InControl ([documentation](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/README.md))
First occurred: 20:50:03 (1 occurrences)
Last logged: 20:50:03

'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/config/custom_components/jlrincontrol/__init__.py", line 396, in async_connect
    self.connection = await self.hass.async_add_executor_job(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jlrpy.py", line 80, in __init__
    self.connect()
  File "/usr/local/lib/python3.12/site-packages/jlrpy.py", line 125, in connect
    self._register_device_and_log_in()
  File "/usr/local/lib/python3.12/site-packages/jlrpy.py", line 130, in _register_device_and_log_in
    self._login_user(self.head)
  File "/usr/local/lib/python3.12/site-packages/jlrpy.py", line 188, in _login_user
    self.user_id = user_data['userId']
                   ~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pmharris77** [comment]
I have seen you have fixed this in v1.7.0.  homeassistant-jlrincontrol is just being updated to use v1.7.0 as we speak :)
